### PR TITLE
fix issue #24: NPE during analysis

### PR DESCRIPTION
**Pull request by MatanRubin**
this is the fix @gcalis suggested in the issue. the suggested fix solves
the issue for me.

### CODE REVIEW

**Comment by ltearno** [comment]
Thank you I have integrated your fix in another commit. Sorry, you won't be in the commit log but i didn't want to rebase such a short commit...
Thanks

**Comment by MatanRubin** [comment]
Not cool

**Comment by ltearno** [comment]
So I reopened the PR, rebased your commit on the master branch so now you are officially in the Pom Explorer commit history! Actually since your commit is on the top of the master branch, your name and picture appear directly on the PomExplorer github page !
Thanks again for your commit and sorry to have duplicated it yesterday, I really thought you wouldn't mind.

**Comment by MatanRubin** [comment]
Hey Itearno, I said that half jokingly, I hope no hard feelings. Thanks for rebasing after all 👍 
This is a very cool project and I look forward to continuing to contribute to it.

**Comment by ltearno** [comment]
No problem, I understand that!
Thanks!

**Pull request closed without merging**
