### PR TITLE
remove unused dependencies and move GraphFrame

### PR DESCRIPTION
**Pull request by robstoll**
As discussed in #40 I removed GraphFrame from pom-explorer-core (had to move it to pom-explorer though). I also removed dependencies which were not used at all (moved them to pom-explorer respectively)

### CODE REVIEW

**Comment by ltearno** [comment]
THank you!

**Comment by ltearno** [comment]
Do you want a ultimate idea license (it has all the jetbrains products inside) ? JetBrains offers such a license for contributors to the project...

**Comment by robstoll** [comment]
@ltearno about the license, why not, might be handy

**Comment by ltearno** [comment]
I will send it to you, is the email rstoll@tutteli.ch correct ?

**Comment by robstoll** [comment]
Yes, that is it

**Pull request merged**
